name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd
      run: cd fastText && ls && make 
    - name: Create Release
      id: create_release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v1')
      with:
        files: | 
          ./fastText/lib/libfasttext-wrapper.a
          ./fastText/obj/libfasttext-wrapper.o
          ./fastText/include/fasttext-wrapper.hpp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      

