name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone fb
      run: git clone https://github.com/facebookresearch/fastText fb
    - name: build fb
      run: cd fb && make && ls
    - name: copy fb
      run: find fb -name '*.o' -exec mv {} fastText/obj \;
    - name: cd
      run: cd fastText && ls && make
    - name: zip
      run: zip -r complete.zip fastText
    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.zip"
        tags: true
        draft: false
        branches: "master;dev"
        verbose: true
