name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone fb
      run: git clone https://github.com/facebookresearch/fastText fb
    - name: build fb
      run: cd fb && make && ls && mv lib ../fastText/lib && mv obj ../fastText/obj
    - name: cd
      run: cd fastText && ls && make && cd .. && zip -r complete.zip fastText  
    - name: Create Release
      id: create_release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.zip"
        tags: true
        draft: false
        branches: "master;dev"
        verbose: true
